### ISSUE TITLE
How do I compile?

### ISSUE THREAD

**Issue by tristanmvh** [leftmostcat/mortar-eng#1]
Hey, I was trying to compile this program with CMake before and worked but then Visual Studio wanted a VCTargetsPath.exe which does not exist.

**Comment by Kaspoehh** [comment]
Hi Tristan, did you ever figure this out?

**Comment by egirlmilkers** [comment]
@tristanmvh @Kaspoehh 
Hello! I was able to figure out how to compile.
I used Fedora (a unix-based environment) inside WSL.

First run this to install all dependencies:
`sudo dnf install git cmake tsl-sparse-map-devel g++ sdl2-devel`

Then clone the repository with:
`git clone https://github.com/leftmostcat/mortar-eng.git`

**NO NEED TO CD INTO THE DIRECTORY**

Then use cmake to build the project and compile it:
`cmake -DCMAKE_BUILD_TYPE=Release -S mortar-eng/ -B mortar-eng/build/`
`cmake --build mortar-eng/build/`

**Comment by dandev10** [comment]
> @tristanmvh @Kaspoehh Hello! I was able to figure out how to compile. I used Fedora (a unix-based environment) inside WSL.
> 
> First run this to install all dependencies: `sudo dnf install git cmake tsl-sparse-map-devel g++ sdl2-devel`
> 
> Then clone the repository with: `git clone https://github.com/leftmostcat/mortar-eng.git`
> 
> **NO NEED TO CD INTO THE DIRECTORY**
> 
> Then use cmake to build the project and compile it: `cmake -DCMAKE_BUILD_TYPE=Release -S mortar-eng/ -B mortar-eng/build/` `cmake --build mortar-eng/build/`

Hi! I´m working from Mac, and i get the following error though:

```bash
[  2%] Building CXX object CMakeFiles/mortar.dir/anim/anim.cpp.o
In file included from /Users/dangon18/trash/mortar-eng/anim/anim.cpp:23:
In file included from /Users/dangon18/trash/mortar-eng/anim/../state.hpp:20:
In file included from /Users/dangon18/trash/mortar-eng/anim/../camera.hpp:17:
In file included from /Users/dangon18/trash/mortar-eng/anim/../math/matrix.hpp:25:
/Users/dangon18/trash/mortar-eng/anim/../math/../streams/stream.hpp:20:10: fatal error: 'SDL2/SDL_rwops.h' file not found
#include <SDL2/SDL_rwops.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/mortar.dir/anim/anim.cpp.o] Error 1
make[1]: *** [CMakeFiles/mortar.dir/all] Error 2
make: *** [all] Error 2
```

SDL2 is installed using homebrew so i dont understand what is it that it doesnt find. That header does exist in the homebrew include folder so...

**Comment by leftmostcat** [comment]
> > @tristanmvh @Kaspoehh Hello! I was able to figure out how to compile. I used Fedora (a unix-based environment) inside WSL.
> > First run this to install all dependencies: `sudo dnf install git cmake tsl-sparse-map-devel g++ sdl2-devel`
> > Then clone the repository with: `git clone https://github.com/leftmostcat/mortar-eng.git`
> > **NO NEED TO CD INTO THE DIRECTORY**
> > Then use cmake to build the project and compile it: `cmake -DCMAKE_BUILD_TYPE=Release -S mortar-eng/ -B mortar-eng/build/` `cmake --build mortar-eng/build/`
> 
> Hi! I´m working from Mac, and i get the following error though:
> 
> ```shell
> [  2%] Building CXX object CMakeFiles/mortar.dir/anim/anim.cpp.o
> In file included from /Users/dangon18/trash/mortar-eng/anim/anim.cpp:23:
> In file included from /Users/dangon18/trash/mortar-eng/anim/../state.hpp:20:
> In file included from /Users/dangon18/trash/mortar-eng/anim/../camera.hpp:17:
> In file included from /Users/dangon18/trash/mortar-eng/anim/../math/matrix.hpp:25:
> /Users/dangon18/trash/mortar-eng/anim/../math/../streams/stream.hpp:20:10: fatal error: 'SDL2/SDL_rwops.h' file not found
> #include <SDL2/SDL_rwops.h>
>          ^~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [CMakeFiles/mortar.dir/anim/anim.cpp.o] Error 1
> make[1]: *** [CMakeFiles/mortar.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> SDL2 is installed using homebrew so i dont understand what is it that it doesnt find. That header does exist in the homebrew include folder so...

Unfortunately, I don't have access to macOS to do testing of my own, but it sounds as though CMake isn't providing the appropriate includes path for SDL2. It's possible that someone in the SDL community (https://discourse.libsdl.org/) may have experienced similar issues with other projects and might be able to help better.

**Comment by bluestation1234** [comment]
Im trying to use this to mod Lego City Undercover But cant compile it with Cmake Can someone help me im on Linux Mint or Ubuntu
